'use client'
import Link from 'next/link'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { apiFetch } from '@/lib/api'

type User={id:string;username:string;email:string;role:string;points:number}
type Match={id:number;teamA:string;teamB:string;event:string;startAt:number;winner:string|null}
type TReg={id:string;tournamentId:string;teamId:string;status:'PENDING'|'APPROVED'|'REJECTED';checkIn:string;team:{name:string;tag:string}|null;tournament:{id:string;name:string}|null}
type Tournament={id:string;name:string;game:string;city:string;venue:string;startAt:number;registrationDeadline:number;teamLimit:number;format:string;prizePool:string;description:string;status:'REGISTRATION'|'UPCOMING'|'LIVE'|'FINISHED'}
type BTeam={id:string;name:string;tag:string}
type BMatch={id:string;round:number;roundLabel:string;teamA:BTeam|null;teamB:BTeam|null;scoreA:number;scoreB:number;status:string;winnerTeam:BTeam|null;scheduledAt?:number;streamUrl?:string}
type Bracket={generated:boolean;rounds:{round:number;label:string;matches:BMatch[]}[]}
const clock=(ts:number)=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))
const inputDate=(ts?:number)=>ts?new Date(ts-new Date(ts).getTimezoneOffset()*60000).toISOString().slice(0,16):''

export default function OrganizerPage(){
  const [me,setMe]=useState<User|null>(null),[users,setUsers]=useState<User[]>([]),[matches,setMatches]=useState<Match[]>([]),[regs,setRegs]=useState<TReg[]>([]),[tournaments,setTournaments]=useState<Tournament[]>([]),[ready,setReady]=useState(false)
  const [selected,setSelected]=useState(''),[bracket,setBracket]=useState<Bracket>({generated:false,rounds:[]}),[msg,setMsg]=useState(''),[scores,setScores]=useState<Record<string,{a:string;b:string}>>({}),[editing,setEditing]=useState<Tournament|null>(null)
  async function load(){try{const auth=await apiFetch<{user:User|null}>('/api/auth/me');setMe(auth.user);if(auth.user&&(auth.user.role==='ADMIN'||auth.user.role==='ORGANIZER')){const [u,m,t]=await Promise.all([apiFetch<{users:User[]}>('/api/organizer/users'),apiFetch<{matches:Match[]}>('/api/matches'),apiFetch<{registrations:TReg[];tournaments:Tournament[]}>('/api/organizer/tournaments')]);setUsers(u.users);setMatches(m.matches);setRegs(t.registrations);setTournaments(t.tournaments);if(!selected&&t.tournaments[0])setSelected(t.tournaments[0].id)}}finally{setReady(true)}}
  async function loadBracket(id=selected){if(!id)return;try{setBracket(await apiFetch<Bracket>(`/api/organizer/bracket?tournamentId=${encodeURIComponent(id)}`))}catch{}}
  useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[])
  useEffect(()=>{if(selected)loadBracket(selected)},[selected])
  async function winner(matchId:number,value:string|null){await apiFetch('/api/organizer/matches',{method:'PATCH',body:JSON.stringify({matchId,winner:value})});await load()}
  async function regStatus(registrationId:string,status:TReg['status']){await apiFetch('/api/organizer/tournaments',{method:'PATCH',body:JSON.stringify({action:'registrationStatus',registrationId,status})});await load()}
  async function tourStatus(tournamentId:string,status:Tournament['status']){await apiFetch('/api/organizer/tournaments',{method:'PATCH',body:JSON.stringify({action:'tournamentStatus',tournamentId,status})});await load()}
  async function points(userId:string,amount:number){await apiFetch('/api/organizer/users',{method:'PATCH',body:JSON.stringify({userId,amount})});await load();window.dispatchEvent(new Event('lan-user-changed'))}
  async function generate(){try{setMsg('');await apiFetch('/api/organizer/bracket',{method:'POST',body:JSON.stringify({tournamentId:selected})});setMsg('Сетка создана. Команды с bye автоматически продвинуты дальше.');await Promise.all([load(),loadBracket()])}catch(e){setMsg(e instanceof Error?e.message:'Ошибка')}}
  async function reset(){if(!confirm('Сбросить турнирную сетку и все результаты внутри неё?'))return;await apiFetch(`/api/organizer/bracket?tournamentId=${encodeURIComponent(selected)}`,{method:'DELETE'});setScores({});setMsg('Сетка сброшена.');await loadBracket()}
  async function setResult(match:BMatch){const s=scores[match.id]||{a:String(match.scoreA||2),b:String(match.scoreB||0)};try{setMsg('');await apiFetch('/api/organizer/bracket',{method:'PATCH',body:JSON.stringify({tournamentId:selected,matchId:match.id,scoreA:Number(s.a),scoreB:Number(s.b)})});setMsg('Результат сохранён, победитель автоматически прошёл дальше.');await Promise.all([load(),loadBracket()])}catch(e){setMsg(e instanceof Error?e.message:'Ошибка')}}
  async function schedule(match:BMatch,scheduledAt:number,streamUrl:string){try{await apiFetch('/api/organizer/bracket',{method:'PATCH',body:JSON.stringify({action:'schedule',tournamentId:selected,matchId:match.id,scheduledAt,streamUrl})});setMsg('Расписание матча обновлено.');await loadBracket()}catch(e){setMsg(e instanceof Error?e.message:'Ошибка')}}
  async function createTournament(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{const result=await apiFetch<{tournament:Tournament}>('/api/organizer/tournaments',{method:'POST',body:JSON.stringify({name:fd.get('name'),game:fd.get('game'),city:fd.get('city'),venue:fd.get('venue'),startAt:new Date(String(fd.get('startAt'))).getTime(),registrationDeadline:new Date(String(fd.get('registrationDeadline'))).getTime(),teamLimit:Number(fd.get('teamLimit')),format:fd.get('format'),prizePool:fd.get('prizePool'),description:fd.get('description')})});setMsg('Турнир создан.');e.currentTarget.reset();await load();setSelected(result.tournament.id)}catch(err){setMsg(err instanceof Error?err.message:'Ошибка')}}
  async function saveEdit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const fd=new FormData(e.currentTarget);try{await apiFetch('/api/organizer/tournaments',{method:'PATCH',body:JSON.stringify({action:'updateTournament',tournamentId:editing.id,name:fd.get('name'),game:fd.get('game'),city:fd.get('city'),venue:fd.get('venue'),startAt:new Date(String(fd.get('startAt'))).getTime(),registrationDeadline:new Date(String(fd.get('registrationDeadline'))).getTime(),teamLimit:Number(fd.get('teamLimit')),format:fd.get('format'),prizePool:fd.get('prizePool'),description:fd.get('description')})});setMsg('Изменения турнира сохранены.');setEditing(null);await load()}catch(err){setMsg(err instanceof Error?err.message:'Ошибка')}}
  const bracketMatches=useMemo(()=>bracket.rounds.flatMap(r=>r.matches),[bracket])
  if(!ready)return null
  if(!me||(me.role!=='ADMIN'&&me.role!=='ORGANIZER'))return <main className="min-h-[calc(100vh-74px)] px-4 py-20"><div className="mx-auto max-w-xl text-center"><div className="text-xs uppercase tracking-[.2em] text-white/35">Закрытый раздел</div><h1 className="mt-3 text-4xl font-black">Только для организатора</h1><Link href="/login" className="mt-6 inline-block rounded-xl bg-[#d94a2c] px-5 py-3 font-bold">Войти как организатор</Link></div></main>
  const pending=regs.filter(r=>r.status==='PENDING').length
  return <main className="min-h-[calc(100vh-74px)] px-4 py-12 md:px-6"><div className="mx-auto max-w-7xl"><div className="mb-8"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#ff7b5d]">Server control center</div><h1 className="mt-2 text-3xl font-black sm:text-4xl md:text-5xl">Панель организатора</h1><p className="mt-3 max-w-2xl text-white/45">Создание турниров, заявки, check-in, расписание матчей, сетка и результаты — всё в одном месте.</p></div>
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Турниры',String(tournaments.length)],['Заявки',String(pending)],['Матчи',String(matches.length+bracketMatches.length)],['Пользователи',String(users.length)]].map(([l,v])=><div key={l} className="card lift rounded-2xl p-5"><div className="text-sm text-white/35">{l}</div><div className="mt-2 text-4xl font-black">{v}</div></div>)}</div>
  {msg&&<div className="mt-5 rounded-xl border border-white/8 bg-black/20 px-4 py-3 text-sm text-white/60">{msg}</div>}

  <section className="card mt-6 rounded-3xl p-6"><div className="flex flex-col gap-5 xl:flex-row"><div className="flex-1"><h2 className="text-2xl font-black">Создать турнир</h2><p className="mt-1 text-sm text-white/40">Новый турнир сразу появится в публичном каталоге.</p><form onSubmit={createTournament} className="mt-5 grid gap-3 md:grid-cols-2"><input name="name" className="field md:col-span-2" placeholder="Название турнира" required/><select name="game" className="field"><option>Dota 2</option><option>Counter-Strike 2</option><option>Valorant</option><option>League of Legends</option></select><input name="city" className="field" placeholder="Город" required/><input name="venue" className="field md:col-span-2" placeholder="Площадка" required/><label className="text-xs text-white/35">Старт<input name="startAt" type="datetime-local" className="field mt-1" required/></label><label className="text-xs text-white/35">Дедлайн регистрации<input name="registrationDeadline" type="datetime-local" className="field mt-1" required/></label><input name="teamLimit" type="number" min="2" max="64" defaultValue="8" className="field" placeholder="Лимит команд"/><input name="prizePool" className="field" placeholder="Призовой фонд, например 100 000 ₽"/><input name="format" className="field md:col-span-2" defaultValue="Double Elimination · BO3"/><textarea name="description" className="field min-h-24 md:col-span-2" placeholder="Описание турнира"/><button className="rounded-xl bg-[#d94a2c] px-5 py-3 font-black md:col-span-2">Создать турнир</button></form></div>
  <div className="w-full xl:max-w-xl"><h2 className="text-2xl font-black">Управление турнирами</h2><div className="mt-5 grid gap-3">{tournaments.map(t=><div key={t.id} className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-bold">{t.name}</div><div className="mt-1 text-xs text-white/35">{t.city} · {t.game}</div></div><button onClick={()=>setEditing(t)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Редактировать</button></div><div className="mt-3"><select value={t.status} onChange={e=>tourStatus(t.id,e.target.value as Tournament['status'])} className="field"><option value="REGISTRATION">REGISTRATION</option><option value="UPCOMING">UPCOMING</option><option value="LIVE">LIVE</option><option value="FINISHED">FINISHED</option></select></div></div>)}</div></div></div></section>

  {editing&&<section className="card mt-6 rounded-3xl p-6"><div className="flex items-center justify-between"><div><div className="text-xs font-black uppercase tracking-[.16em] text-[#ff8064]">Edit tournament</div><h2 className="mt-1 text-2xl font-black">{editing.name}</h2></div><button onClick={()=>setEditing(null)} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Закрыть</button></div><form onSubmit={saveEdit} className="mt-5 grid gap-3 md:grid-cols-2"><input name="name" defaultValue={editing.name} className="field md:col-span-2"/><input name="game" defaultValue={editing.game} className="field"/><input name="city" defaultValue={editing.city} className="field"/><input name="venue" defaultValue={editing.venue} className="field md:col-span-2"/><input name="startAt" type="datetime-local" defaultValue={inputDate(editing.startAt)} className="field"/><input name="registrationDeadline" type="datetime-local" defaultValue={inputDate(editing.registrationDeadline)} className="field"/><input name="teamLimit" type="number" min="2" max="64" defaultValue={editing.teamLimit} className="field"/><input name="prizePool" defaultValue={editing.prizePool} className="field"/><input name="format" defaultValue={editing.format} className="field md:col-span-2"/><textarea name="description" defaultValue={editing.description} className="field min-h-24 md:col-span-2"/><button className="rounded-xl bg-emerald-500/15 px-5 py-3 font-black text-emerald-200 md:col-span-2">Сохранить изменения</button></form></section>}

  <section className="card mt-6 rounded-3xl p-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black">Заявки на турниры</h2><p className="mt-1 text-sm text-white/40">Одобряй команды и допускай их к check-in.</p></div><span className="text-sm text-white/35">{regs.length}</span></div><div className="mt-5 grid gap-3">{regs.length===0?<div className="text-sm text-white/35">Заявок пока нет.</div>:regs.map(r=><div key={r.id} className="rounded-2xl border border-white/8 bg-white/[.025] p-4 md:flex md:items-center md:justify-between"><div><div className="font-bold">{r.team?.name||'Команда'} <span className="text-white/35">[{r.team?.tag}]</span></div><div className="mt-1 text-sm text-white/40">{r.tournament?.name||'Турнир'} · check-in: {r.checkIn}</div></div><div className="mt-3 flex flex-wrap gap-2 md:mt-0"><button onClick={()=>regStatus(r.id,'APPROVED')} className="rounded-lg bg-emerald-400/10 px-3 py-2 text-xs font-bold text-emerald-200">Одобрить</button><button onClick={()=>regStatus(r.id,'REJECTED')} className="rounded-lg bg-red-400/10 px-3 py-2 text-xs font-bold text-red-200">Отклонить</button><button onClick={()=>regStatus(r.id,'PENDING')} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Pending</button><span className="rounded-lg border border-white/8 px-3 py-2 text-xs text-white/40">{r.status}</span></div></div>)}</div></section>

  <section className="card mt-6 rounded-3xl p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-black uppercase tracking-[.16em] text-[#ff8064]">Bracket engine</div><h2 className="mt-1 text-3xl font-black">Сетка и расписание</h2><p className="mt-2 text-sm text-white/40">Для каждого матча можно назначить время и ссылку на трансляцию.</p></div><div className="flex flex-wrap gap-2"><select value={selected} onChange={e=>setSelected(e.target.value)} className="field w-full sm:min-w-60">{tournaments.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={generate} className="rounded-xl bg-[#d94a2c] px-4 py-3 text-sm font-black">Сгенерировать</button>{bracket.generated&&<button onClick={reset} className="rounded-xl border border-red-400/20 bg-red-400/5 px-4 py-3 text-sm font-bold text-red-200">Сбросить</button>}</div></div>
  {!bracket.generated?<div className="mt-5 rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-white/35">Сетка ещё не создана.</div>:<div className="mt-6 overflow-x-auto pb-3"><div className="flex min-w-max gap-6">{bracket.rounds.map(round=><div key={round.round} className="w-[330px]"><div className="mb-3 text-xs font-black uppercase tracking-[.16em] text-[#ff8064]">{round.label}</div><div className="space-y-4">{round.matches.map(m=><BracketMatchCard key={m.id} match={m} score={scores[m.id]||{a:String(m.scoreA||2),b:String(m.scoreB||0)}} setScore={(next)=>setScores(v=>({...v,[m.id]:next}))} onResult={()=>setResult(m)} onSchedule={schedule}/>)}</div></div>)}</div></div>}</section>

  <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="card rounded-3xl p-6"><h2 className="text-2xl font-black">Прогнозные матчи</h2><div className="mt-5 space-y-3">{matches.map(m=><div key={m.id} className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="text-xs text-white/35">{m.event} · {clock(m.startAt)}</div><div className="mt-2 flex justify-between gap-3 font-bold"><span>{m.teamA}</span><span>{m.teamB}</span></div>{m.winner&&<div className="mt-2 text-xs text-emerald-300">Победитель: {m.winner}</div>}<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>winner(m.id,m.teamA)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{m.teamA}</button><button onClick={()=>winner(m.id,m.teamB)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{m.teamB}</button></div><button onClick={()=>winner(m.id,null)} className="mt-2 w-full rounded-lg border border-white/8 px-3 py-2 text-xs text-white/40">Сбросить результат</button></div>)}</div></section><section className="card rounded-3xl p-6"><h2 className="text-2xl font-black">Пользователи и LAN Points</h2><div className="mt-5 space-y-3">{users.map(u=><div key={u.id} className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="font-bold">{u.username}</div><div className="mt-1 text-xs text-white/35">{u.email} · {u.role}</div><div className="mt-4 flex items-center justify-between"><span className="text-xl font-black">{u.points} LP</span><div className="flex gap-2"><button onClick={()=>points(u.id,100)} className="rounded-lg bg-[#d94a2c]/10 px-3 py-2 text-xs font-bold text-[#ff8a70]">+100</button><button onClick={()=>points(u.id,500)} className="rounded-lg bg-[#d94a2c]/10 px-3 py-2 text-xs font-bold text-[#ff8a70]">+500</button></div></div></div>)}</div></section></div>
  </div></main>
}

function BracketMatchCard({match,score,setScore,onResult,onSchedule}:{match:BMatch;score:{a:string;b:string};setScore:(v:{a:string;b:string})=>void;onResult:()=>void;onSchedule:(m:BMatch,t:number,u:string)=>void}){
  const [when,setWhen]=useState(inputDate(match.scheduledAt)),[stream,setStream]=useState(match.streamUrl||'')
  useEffect(()=>{setWhen(inputDate(match.scheduledAt));setStream(match.streamUrl||'')},[match.scheduledAt,match.streamUrl])
  return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-center justify-between gap-3"><span className={`truncate font-bold ${match.winnerTeam?.id===match.teamA?.id?'text-emerald-300':''}`}>{match.teamA?`${match.teamA.name} [${match.teamA.tag}]`:'TBD'}</span><input disabled={match.status!=='READY'} value={score.a} onChange={e=>setScore({a:e.target.value,b:score.b})} className="w-12 rounded-lg border border-white/10 bg-black/30 px-2 py-1 text-center font-black outline-none"/></div><div className="my-2 h-px bg-white/6"/><div className="flex items-center justify-between gap-3"><span className={`truncate font-bold ${match.winnerTeam?.id===match.teamB?.id?'text-emerald-300':''}`}>{match.teamB?`${match.teamB.name} [${match.teamB.tag}]`:'TBD'}</span><input disabled={match.status!=='READY'} value={score.b} onChange={e=>setScore({a:score.a,b:e.target.value})} className="w-12 rounded-lg border border-white/10 bg-black/30 px-2 py-1 text-center font-black outline-none"/></div><div className="mt-3 grid gap-2"><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} className="field text-xs"/><input value={stream} onChange={e=>setStream(e.target.value)} className="field text-xs" placeholder="Ссылка на трансляцию (необязательно)"/><div className="grid gap-2 sm:flex"><button onClick={()=>onSchedule(match,when?new Date(when).getTime():0,stream)} className="flex-1 rounded-lg border border-white/10 px-3 py-2 text-xs font-bold">Сохранить время</button><Link href={`/matches/${match.id}`} className="rounded-lg border border-white/10 px-3 py-2 text-center text-xs font-bold">Страница</Link></div></div><div className="mt-3 flex items-center justify-between gap-2"><span className="text-[10px] font-black uppercase tracking-[.12em] text-white/25">{match.status}</span>{match.status==='READY'&&<button onClick={onResult} className="rounded-lg bg-emerald-400/10 px-3 py-2 text-xs font-black text-emerald-200">Сохранить результат</button>}</div></div>
}
