'use client'

import Link from 'next/link'
import { use, useEffect, useState } from 'react'
import { apiFetch } from '@/lib/api'

type Team={id:string;name:string;tag:string;members:{position:string}[]}
type Reg={id:string;status:'PENDING'|'APPROVED'|'REJECTED';checkIn:'NOT_CHECKED_IN'|'CHECKED_IN'}
type T={id:string;name:string;game:string;city:string;venue:string;startAt:number;registrationDeadline:number;teamLimit:number;format:string;prizePool:string;status:string;description:string;approvedCount:number;spotsLeft:number}
type Data={tournament:T;myTeam:Team|null;myRegistration:Reg|null;registrations:{id:string;checkIn:string;team:Team|null}[]}
type BracketTeam={id:string;name:string;tag:string}
type BracketMatch={id:string;round:number;roundLabel:string;slot:number;teamA:BracketTeam|null;teamB:BracketTeam|null;scoreA:number;scoreB:number;winnerTeam:BracketTeam|null;status:'WAITING'|'READY'|'FINISHED'}
type Bracket={generated:boolean;rounds:{round:number;label:string;matches:BracketMatch[]}[]}
const fmt=(ts:number)=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'long',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))

function BracketBoard({data}:{data:Bracket}){
  if(!data.generated)return <div className="rounded-2xl border border-dashed border-white/10 bg-white/[.02] p-8 text-center text-sm text-white/35">Сетка ещё не сформирована организатором.</div>
  return <div className="overflow-x-auto pb-3"><div className="flex min-w-max gap-6">{data.rounds.map(round=><div key={round.round} className="w-[280px]"><div className="mb-3 text-xs font-black uppercase tracking-[.16em] text-[#ff8064]">{round.label}</div><div className="flex min-h-[260px] flex-col justify-around gap-4">{round.matches.map(match=><div key={match.id} className="rounded-2xl border border-white/8 bg-black/25 p-3 shadow-[0_18px_60px_rgba(0,0,0,.22)]"><div className="flex items-center justify-between gap-3 rounded-xl px-3 py-2"><div className={`truncate text-sm font-bold ${match.winnerTeam?.id===match.teamA?.id?'text-emerald-300':'text-white/80'}`}>{match.teamA?`${match.teamA.name} [${match.teamA.tag}]`:'TBD'}</div><div className="text-lg font-black">{match.status==='FINISHED'?match.scoreA:'–'}</div></div><div className="my-1 h-px bg-white/6"/><div className="flex items-center justify-between gap-3 rounded-xl px-3 py-2"><div className={`truncate text-sm font-bold ${match.winnerTeam?.id===match.teamB?.id?'text-emerald-300':'text-white/80'}`}>{match.teamB?`${match.teamB.name} [${match.teamB.tag}]`:'TBD'}</div><div className="text-lg font-black">{match.status==='FINISHED'?match.scoreB:'–'}</div></div><div className="mt-2 text-[10px] font-bold uppercase tracking-[.12em] text-white/25">{match.status==='READY'?'готов к матчу':match.status==='FINISHED'?'завершён':'ожидает соперников'}</div></div>)}</div></div>)}</div></div>
}

export default function TournamentPage({params}:{params:Promise<{id:string}>}){
  const {id}=use(params)
  const [data,setData]=useState<Data|null>(null),[bracket,setBracket]=useState<Bracket>({generated:false,rounds:[]}),[error,setError]=useState(''),[notice,setNotice]=useState('')
  async function load(){try{const [main,b]=await Promise.all([apiFetch<Data>(`/api/tournaments/${id}`),apiFetch<Bracket>(`/api/tournaments/${id}/bracket`)]);setData(main);setBracket(b);setError('')}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
  useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[id])
  async function register(){try{await apiFetch(`/api/tournaments/${id}/register`,{method:'POST'});setNotice('Заявка отправлена организатору.');await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
  async function checkin(){try{await apiFetch(`/api/tournaments/${id}/checkin`,{method:'POST'});setNotice('Check-in пройден.');await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
  if(!data)return <main className="mx-auto max-w-7xl px-4 py-14 md:px-6"><div className="text-white/40">{error||'Загрузка...'}</div></main>
  const t=data.tournament
  return <main className="mx-auto max-w-7xl px-4 py-12 md:px-6"><Link href="/tournaments" className="text-sm text-white/40 hover:text-white">← Все турниры</Link><section className="mt-5 card rounded-3xl p-6 md:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-3xl"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#ff7b5d]">{t.game} · {t.city}</div><h1 className="mt-2 text-4xl font-black md:text-5xl">{t.name}</h1><p className="mt-4 leading-7 text-white/50">{t.description}</p></div><div className="min-w-64 rounded-2xl border border-white/8 bg-black/20 p-5"><div className="text-sm text-white/35">Призовой фонд</div><div className="mt-1 text-3xl font-black">{t.prizePool}</div><div className="mt-4 text-sm text-white/35">{t.approvedCount}/{t.teamLimit} команд · {t.spotsLeft} мест</div><div className="mt-2 inline-flex rounded-full border border-[#ff7b5d]/20 bg-[#ff7b5d]/8 px-3 py-1 text-xs font-bold text-[#ff9b83]">{t.status}</div></div></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Старт',fmt(t.startAt)],['Дедлайн',fmt(t.registrationDeadline)],['Формат',t.format],['Площадка',t.venue]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="text-xs text-white/30">{a}</div><div className="mt-1 font-bold">{b}</div></div>)}</div></section>
  {error&&<div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</div>}{notice&&<div className="mt-5 rounded-xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">{notice}</div>}
  <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="card rounded-3xl p-6"><h2 className="text-2xl font-black">Участие</h2>{!data.myTeam?<p className="mt-4 text-sm text-white/45">Чтобы зарегистрироваться, сначала создай команду или вступи в неё.</p>:data.myRegistration?<div className="mt-5 rounded-2xl border border-white/8 bg-white/[.025] p-5"><div className="font-bold">Команда {data.myTeam.name}</div><div className="mt-2 text-sm text-white/45">Статус заявки: <span className="text-white">{data.myRegistration.status}</span></div><div className="mt-1 text-sm text-white/45">Check-in: <span className="text-white">{data.myRegistration.checkIn}</span></div>{data.myRegistration.status==='APPROVED'&&data.myRegistration.checkIn!=='CHECKED_IN'&&<button onClick={checkin} className="mt-4 rounded-xl bg-[#d94a2c] px-4 py-3 font-bold">Пройти check-in</button>}</div>:<><p className="mt-4 text-sm text-white/45">Заявку может отправить только капитан. Для Dota 2 должны быть заняты позиции 1–5.</p><button onClick={register} className="mt-5 rounded-xl bg-[#d94a2c] px-5 py-3 font-bold">Зарегистрировать команду</button></>}</section><section className="card rounded-3xl p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Участники</h2><span className="text-sm text-white/35">{data.registrations.length}</span></div><div className="mt-5 space-y-3">{data.registrations.length===0?<div className="text-sm text-white/35">Одобренных команд пока нет.</div>:data.registrations.map(r=><div key={r.id} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.025] px-4 py-3"><div><div className="font-bold">{r.team?.name||'Команда'}</div><div className="text-xs text-white/35">[{r.team?.tag}]</div></div><span className={`text-xs font-bold ${r.checkIn==='CHECKED_IN'?'text-emerald-300':'text-white/35'}`}>{r.checkIn==='CHECKED_IN'?'CHECKED IN':'WAITING'}</span></div>)}</div></section></div>
  <section className="card mt-6 rounded-3xl p-5 md:p-6"><div className="mb-5 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-black uppercase tracking-[.18em] text-[#ff8064]">Tournament bracket</div><h2 className="mt-1 text-3xl font-black">Турнирная сетка</h2></div><div className="text-sm text-white/35">Обновляется автоматически каждые 5 секунд</div></div><BracketBoard data={bracket}/></section>
  </main>
}
